export const MOCK_EVENTS = [
  {
    id: "1",
    title: "GateOn Tech Meetup: Building Modern Event Platforms",
    date: "Fri, Feb 20 · 6:30 PM",
    location: "Bengaluru · In person",
    category: "Tech",
    status: "published",
    ownerId: "user-1",
    trending: true,
    rating: 4.6,
    venueType: "In person",
    price: 0,
    attendees: 92,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Access to the full event.",
        price: 0,
        maxQuantity: 120,
        saleStart: "",
        saleEnd: "",
      },
      {
        id: "vip",
        label: "VIP",
        description: "Priority seating and networking.",
        price: 999,
        maxQuantity: 20,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "2",
    title: "Indie Night: Live Music in the City",
    date: "Sat, Feb 28 · 8:00 PM",
    location: "Mumbai · In person",
    category: "Music",
    status: "published",
    ownerId: "user-1",
    trending: true,
    rating: 4.2,
    venueType: "In person",
    price: 499,
    attendees: 180,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Entry ticket to the show.",
        price: 499,
        maxQuantity: 300,
        saleStart: "",
        saleEnd: "",
      },
      {
        id: "early",
        label: "Early Bird",
        description: "Limited discounted tickets.",
        price: 399,
        maxQuantity: 50,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "3",
    title: "Startup Funding 101 – Investor AMA",
    date: "Sun, Mar 3 · 11:00 AM",
    location: "Online · Webinar",
    category: "Business",
    status: "published",
    ownerId: "user-1",
    trending: false,
    rating: 4.8,
    venueType: "Online",
    price: 299,
    attendees: 320,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Access to the live session.",
        price: 299,
        maxQuantity: 500,
        saleStart: "",
        saleEnd: "",
      },
      {
        id: "student",
        label: "Student",
        description: "Discounted student ticket.",
        price: 199,
        maxQuantity: 100,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1556761175-5973dc0f32e7?ixlib=rb-4.0.3&auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "4",
    title: "City Marathon Training Run",
    date: "Sat, Mar 9 · 6:00 AM",
    location: "Delhi NCR · In person",
    category: "Sports",
    status: "published",
    ownerId: "user-1",
    trending: true,
    rating: 4.1,
    venueType: "In person",
    sportType: "Running",
    price: 199,
    attendees: 260,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Group run + hydration points.",
        price: 199,
        maxQuantity: 400,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1520975916090-3105956dac38?auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "5",
    title: "Weekend Badminton Doubles League",
    date: "Sun, Mar 10 · 9:00 AM",
    location: "Bengaluru · In person",
    category: "Sports",
    status: "published",
    ownerId: "user-1",
    trending: false,
    rating: 4.7,
    venueType: "In person",
    sportType: "Badminton",
    price: 299,
    attendees: 140,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Team registration.",
        price: 299,
        maxQuantity: 120,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "6",
    title: "Football 5-a-side Night",
    date: "Fri, Mar 15 · 8:30 PM",
    location: "Mumbai · In person",
    category: "Sports",
    status: "published",
    ownerId: "user-1",
    trending: true,
    rating: 4.4,
    venueType: "In person",
    sportType: "Football",
    price: 249,
    attendees: 88,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Includes ground booking.",
        price: 249,
        maxQuantity: 120,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1518600506278-4e8ef466b810?auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "7",
    title: "Remote React Workshop",
    date: "Wed, Mar 20 · 7:00 PM",
    location: "Online · Workshop",
    category: "Tech",
    status: "published",
    ownerId: "user-1",
    trending: false,
    rating: 4.9,
    venueType: "Online",
    price: 599,
    attendees: 410,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Live session + recordings.",
        price: 599,
        maxQuantity: 600,
        saleStart: "",
        saleEnd: "",
      },
      {
        id: "student",
        label: "Student",
        description: "Discounted student access.",
        price: 399,
        maxQuantity: 150,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "8",
    title: "Creator Meetup: Growth & Branding",
    date: "Sat, Mar 23 · 4:00 PM",
    location: "Hyderabad · In person",
    category: "Business",
    status: "published",
    ownerId: "user-1",
    trending: true,
    rating: 4.3,
    venueType: "In person",
    price: 0,
    attendees: 520,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Free entry (limited seats).",
        price: 0,
        maxQuantity: 200,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1559223607-a43c990c692c?auto=format&fit=crop&w=1000&q=80",
  },
  {
    id: "9",
    title: "Cricket Turf Match: Sunday League",
    date: "Sun, Mar 24 · 5:00 PM",
    location: "Chennai · In person",
    category: "Sports",
    status: "published",
    ownerId: "user-1",
    trending: false,
    rating: 4.0,
    venueType: "In person",
    sportType: "Cricket",
    price: 349,
    attendees: 64,
    tickets: [
      {
        id: "general",
        label: "General",
        description: "Team slot booking.",
        price: 349,
        maxQuantity: 80,
        saleStart: "",
        saleEnd: "",
      },
    ],
    image:
      "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1000&q=80",
  },
];
